"""App revision — single source of truth.

The revision is git-derived: base MAJOR.MINOR from ./VERSION, patch = commit
count, pinned by short SHA + branch + commit date. scripts/gen-revision.sh
stamps it into revision.json (regenerated by the git hooks on commit/push);
that file is bind-mounted read-only into the api container. Read at runtime so a
push refreshes the reported version without an api rebuild. Falls back to a dev
stub when the file is absent (fresh checkout before the hooks ran).
"""

from __future__ import annotations

import json
import os

_DEV_REVISION: dict = {
    "version": "0.0.0-dev",
    "base": "0.0",
    "count": 0,
    "sha": "unknown",
    "branch": "unknown",
    "committed_at": None,
    "dirty": True,
}
_REVISION_FILE = os.environ.get("BABA_REVISION_FILE", "/app/revision.json")


def revision() -> dict:
    """The full revision record (product/version/base/count/sha/branch/committed_at/dirty).
    `product` is how a peer on the network tells a BABA from another install that
    also serves /version."""
    try:
        with open(_REVISION_FILE, encoding="utf-8") as fh:
            return {"product": "baba", **json.load(fh)}
    except (OSError, ValueError):
        return {"product": "baba", **_DEV_REVISION}


def version_string() -> str:
    """Just the display version, e.g. "0.1.68"."""
    return revision().get("version", _DEV_REVISION["version"])
