# shellcheck shell=bash
# .env file generator:
#
#   envgen_write          → create fresh .env from current values (first install)
#   envgen_merge_missing  → re-read existing .env, append only keys it's missing
#   envgen_apply          → set the named keys to the wizard's values (reconfigure)
#   envgen_retire         → drop keys this version no longer reads (upgrade, deploy)
#
# Critical invariant: secrets are NEVER overwritten. The wizard reads
# BABA_SECRET_KEY and the passwords back from .env before anything is
# written, so a reconfigure hands envgen_apply the values already there
# (a new key would invalidate every signed JWT in flight).

# Copy .env to .env.bak.<stamp> before a change. One run may change the file
# in several steps within a second (retire, merge, apply): the first backup of
# that second is the pre-run state, so a later step never overwrites it.
envgen_backup() {
    local target="$1" bak
    bak="${target}.bak.$(date +%Y%m%d-%H%M%S)"
    [[ -e "$bak" ]] && return 0
    cp "$target" "$bak"
    chmod 600 "$bak"
    c_dim "  Backed up existing .env → $bak"
}

# All keys we know about. Order is preserved on write so the produced
# .env stays diff-friendly across versions. Comments + section headers
# live in the template below; values come from the matching shell vars.
envgen_write() {
    local target="$1"
    # Backup any existing file so the operator can roll back if the
    # wizard wrote something they don't like.
    [[ -f "$target" ]] && envgen_backup "$target"

    # The template uses parameter expansion so empty vars come out as
    # empty values, never as the literal `${VAR}` text. Created 600 before
    # any secret is written: the file carries BABA_SECRET_KEY and every
    # service password, so it must never land world-readable under the
    # operator's umask.
    (umask 077; : > "$target")
    cat > "$target" <<EOF
# BABA configuration — generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Re-running install.sh appends keys missing from this file; only
# --reconfigure changes existing values, and only the ones its wizard asks about.

# =========================================================================
# Storage paths (host)
# =========================================================================
BABA_MODELS_HOST=${BABA_MODELS_HOST}
BABA_STATE_HOST=${BABA_STATE_HOST}
BABA_MEDIA_HOST=${BABA_MEDIA_HOST}

# Runtime uid:gid for the non-root service containers. The bundled images bake
# user 1000; the host storage tiers (models, media, state/api) are chowned to
# this by install.sh so the containers can write. Change only if you rebuilt
# the images with a different uid.
BABA_UID=${BABA_UID}
BABA_GID=${BABA_GID}

# =========================================================================
# Resource governance (shared-host only — leave empty on a dedicated host)
# =========================================================================
# When BABA shares a host with other stacks, cap/prioritise the baba.slice
# cgroup (every container runs under it). Empty = unconstrained. Applied by
# install.sh via 'systemctl set-property' (live + persists reboots).
#   BABA_MEM_LIMIT: hard memory ceiling for ALL baba containers, e.g. 8G.
#     Exceeding it OOM-kills the largest baba process (protects co-tenants).
#   BABA_CPU_WEIGHT: scheduler weight (default 100). 1000 = 10x priority under
#     contention; soft (no idle waste), protects BABA's real-time pipeline.
BABA_MEM_LIMIT=${BABA_MEM_LIMIT:-}
BABA_CPU_WEIGHT=${BABA_CPU_WEIGHT:-}

# =========================================================================
# Hardware variant
# =========================================================================
# cpu | nvidia | intel. Detected by install.sh; override here for testing.
BABA_VARIANT=${BABA_VARIANT}

# Which compose files 'docker compose' merges: the hardware-neutral base plus
# the GPU override for this variant (nvidia/intel). Set by install.sh from the
# variant so plain 'docker compose' commands on the host pick up the right
# deploy layer. Keep in sync with BABA_VARIANT if you change it by hand.
COMPOSE_FILE=${COMPOSE_FILE}

# The image tag for this checkout, written by install.sh: on a release tag it is
# that release's version and pins its <variant>-<version> images; empty takes
# the moving <variant> tag. It follows the checkout, so it is not edited by hand.
BABA_IMAGE_TAG=${BABA_IMAGE_TAG}

# The ingestor's one video decoder. Empty = the variant's (ffmpeg-nvdec-nv12
# on nvidia, vaapi-nv12 on intel, software on cpu). Named only for a host the
# default does not suit: an Intel iGPU gets qsv-nv12 (install.sh sets it).
BABA_DECODER_BACKEND=${BABA_DECODER_BACKEND:-}

# Host 'render' group gid, added to the intel GPU services (group_add) so the
# uid-1000 containers can open /dev/dri/renderD128. Detected by install.sh on
# the intel variant (Debian 993, Ubuntu 110). Only used by docker-compose.intel.yml.
BABA_INTEL_RENDER_GID=${BABA_INTEL_RENDER_GID:-110}

# =========================================================================
# Detector
# =========================================================================
# The backend follows the variant: tensorrt / openvino / onnxruntime.
# Set by install.sh: nv12-baked graph on nvidia (the GPU decoders write NV12),
# nv12-baked or plain on intel (OpenVINO wraps a plain one), plain on cpu.
BABA_DETECTOR_MODEL=${BABA_DETECTOR_MODEL}
# Detector head family: "dfine" (D-FINE / RT-DETR, plain [0,1] input) or
# "rfdetr" (RF-DETR / LWDETR, 91-class dets+labels output, ImageNet norm +
# square stretch). Set by install.sh from the GPU tier (detect_gpu_tier):
# a discrete GPU (Arc) gets rfdetr, a budget iGPU gets the lighter dfine CNN.
BABA_DETECTOR_MODEL_FAMILY=${BABA_DETECTOR_MODEL_FAMILY:-dfine}
# OpenVINO inference precision override (f16 | f32). Empty = backend self-selects
# (it verifies fp16 stability per model). install.sh sets f16 for RF-DETR on Arc.
BABA_DETECTOR_OV_PRECISION=${BABA_DETECTOR_OV_PRECISION:-}
BABA_DETECTOR_BATCH=8
BABA_DETECTOR_BATCH_WAIT_MS=20
BABA_DETECTOR_CONF=0.10
BABA_DETECTOR_IOU=0.45
BABA_DETECTOR_INPUT_SIZE=640
BABA_DEVICE_ID=0

# =========================================================================
# Tracker (Norfair IoU+Kalman + inline appearance re-ID)
# =========================================================================
BABA_TRACKER_CLASSES=0,1,2,3,5,7,14,15,16
BABA_TRACKER_FPS=15

# =========================================================================
# Embedder (DINOv2 body re-ID + AuraFace face re-ID)
# =========================================================================
BABA_EMBEDDER_MODEL=/models/osnet_x0_25_msmt17.onnx
BABA_FACE_DETECTOR_MODEL=/models/face_yunet.onnx
BABA_FACE_EMBEDDER_MODEL=/models/face_auraface.onnx

# =========================================================================
# Plate reading (state evaluator) — BYOM, off while empty
# =========================================================================
# Not BABA's to ship: the detector derives from YOLOv9 (GPL-3.0) and the OCR
# weights carry no licence statement (LICENSES.md). Naming both fetches them
# from their authors' releases on first start, under terms that are yours.
# Detector: yolov9_s_608 | yolov9_t_384. OCR: cct_s_v1_global | european_vit_v2.
BABA_PLATE_DETECTOR=${BABA_PLATE_DETECTOR:-}
BABA_PLATE_OCR=${BABA_PLATE_OCR:-}

# =========================================================================
# Event manager
# =========================================================================
BABA_EVENT_TRACK_TIMEOUT_MS=5000
BABA_EVENT_MIN_TRACK_LIFETIME_MS=1500
BABA_EVENT_MIN_OBSERVATIONS=5
BABA_THUMBNAIL_MAX_WIDTH=640
BABA_EVENT_DWELL_MS=30000

# =========================================================================
# Recorder
# =========================================================================
BABA_RECORDER_SEGMENT_SECONDS=300

# =========================================================================
# Postgres
# =========================================================================
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB}
# Empty = asyncpg default (right for the bundled non-TLS Postgres).
# Set to 'require' or 'verify-full' for external managed Postgres.
POSTGRES_SSLMODE=${POSTGRES_SSLMODE}

# =========================================================================
# NATS authentication
# =========================================================================
# Required: the bus never runs open. The server is given only bcrypt hashes
# (docker/nats-start.sh) and every client URL carries these. Generated once;
# changing them logs out every connected service and mirror.
NATS_USER=${NATS_USER}
NATS_PASSWORD=${NATS_PASSWORD}

# The account a remote mirror (DIDA's baba adapter) logs in with: read-only, it
# may subscribe to state and bell and ask for the roster and nothing else. It
# lives in the same config as the service account, so an empty password here
# would be an account with no password rather than no account — the bus refuses
# to start instead. Generated with the service credentials and handed to a
# mirror when one is set up; its replies come back under `_INBOX.dida`.
BABA_PEER_NATS_PASSWORD=${BABA_PEER_NATS_PASSWORD}

# =========================================================================
# go2rtc REST API auth
# =========================================================================
# go2rtc runs network_mode:host, so its :1984 API is exposed on every host
# interface. Without a password any LAN host can read every camera's plaintext
# RTSP credentials via /api/config. install.sh generates a password; empty
# leaves the API open (legacy). All internal clients present these creds.
BABA_GO2RTC_API_USER=${BABA_GO2RTC_API_USER}
BABA_GO2RTC_API_PASSWORD=${BABA_GO2RTC_API_PASSWORD}

# =========================================================================
# API
# =========================================================================
BABA_API_PORT=${BABA_API_PORT}
BABA_ADMIN_USERNAME=${BABA_ADMIN_USERNAME}
# Empty = api generates a random password on first boot and persists it
# to \${BABA_STATE_HOST}/api/bootstrap_admin_password. Set here only if
# you want to override (e.g. CI tests).
BABA_ADMIN_PASSWORD=${BABA_ADMIN_PASSWORD}
# Required: signs JWT cookies. install.sh generated this once;
# never change without accepting that every active session breaks.
BABA_SECRET_KEY=${BABA_SECRET_KEY}
# true behind HTTPS, false for plain-HTTP localhost dev.
BABA_COOKIE_SECURE=${BABA_COOKIE_SECURE}
# Origins allowed to call the API. Empty = dev defaults (localhost:5173).
# Set to your public hostname(s) when behind a reverse proxy.
BABA_CORS_ORIGINS=${BABA_CORS_ORIGINS}

# AI auto-describe loop — off by default (per-call cost to Anthropic / OpenAI).
BABA_AI_AUTO_DESCRIBE=0
BABA_AI_AUTO_DESCRIBE_INTERVAL_S=120
BABA_AI_AUTO_DESCRIBE_BATCH=5
EOF
    chmod 600 "$target"
    c_ok "Wrote $target"
}

# Add any keys from the current shell's set that the existing .env is
# missing. Used on re-run / upgrade so a newly-added variable lands in
# the file without disturbing what the operator already set. Returns
# the number of keys appended.
envgen_merge_missing() {
    local target="$1"
    if [[ ! -f "$target" ]]; then
        c_err "envgen_merge_missing: $target does not exist"
        return 1
    fi
    # Known keys this version of install.sh wants present. Keep in
    # sync with envgen_write's template. Skip values: we don't seed
    # passwords / secrets on merge — those have their own gen path.
    local keys=(
        BABA_MODELS_HOST BABA_STATE_HOST BABA_MEDIA_HOST
        BABA_UID BABA_GID
        BABA_MEM_LIMIT BABA_CPU_WEIGHT
        BABA_VARIANT COMPOSE_FILE BABA_IMAGE_TAG BABA_DECODER_BACKEND BABA_INTEL_RENDER_GID
        BABA_DETECTOR_MODEL
        BABA_DETECTOR_MODEL_FAMILY BABA_DETECTOR_OV_PRECISION BABA_DETECTOR_BATCH
        BABA_DETECTOR_BATCH_WAIT_MS BABA_DETECTOR_CONF BABA_DETECTOR_IOU
        BABA_DETECTOR_INPUT_SIZE BABA_DEVICE_ID
        BABA_TRACKER_CLASSES BABA_TRACKER_FPS
        BABA_EMBEDDER_MODEL BABA_FACE_DETECTOR_MODEL BABA_FACE_EMBEDDER_MODEL
        BABA_PLATE_DETECTOR BABA_PLATE_OCR
        BABA_EVENT_TRACK_TIMEOUT_MS BABA_EVENT_MIN_TRACK_LIFETIME_MS
        BABA_EVENT_MIN_OBSERVATIONS BABA_THUMBNAIL_MAX_WIDTH BABA_EVENT_DWELL_MS
        BABA_RECORDER_SEGMENT_SECONDS
        POSTGRES_USER POSTGRES_PASSWORD POSTGRES_DB POSTGRES_SSLMODE
        NATS_USER NATS_PASSWORD BABA_PEER_NATS_PASSWORD
        BABA_GO2RTC_API_USER BABA_GO2RTC_API_PASSWORD
        BABA_API_PORT BABA_ADMIN_USERNAME BABA_ADMIN_PASSWORD BABA_SECRET_KEY
        BABA_COOKIE_SECURE BABA_CORS_ORIGINS
        BABA_AI_AUTO_DESCRIBE BABA_AI_AUTO_DESCRIBE_INTERVAL_S BABA_AI_AUTO_DESCRIBE_BATCH
    )
    # Heal perms on a legacy .env that predates the 600 default.
    chmod 600 "$target"
    local appended=0
    local k
    for k in "${keys[@]}"; do
        if ! grep -qE "^${k}=" "$target"; then
            local v
            v="$(envgen_default_for "$k")"
            {
                printf '\n# Added by install.sh on %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
                printf '%s=%s\n' "$k" "$v"
            } >> "$target"
            appended=$((appended+1))
        fi
    done
    if (( appended > 0 )); then
        c_ok "Appended $appended new key(s) to $target"
    else
        c_dim "  No new keys to merge — .env up to date."
    fi
}

# Keys this version no longer reads. Each backend now follows the service's
# variant; a retired key left in .env would read as if it still chose one.
ENVGEN_RETIRED_KEYS=(
    BABA_DECODER_BACKENDS BABA_DETECTOR_BACKENDS BABA_DETECTOR_GPU_NV12
    BABA_INFERENCE_PROVIDERS BABA_API_INFERENCE_PROVIDERS
    BABA_REQUIRE_GPU BABA_REQUIRE_HW_DECODE
)

# The decoder an old BABA_DECODER_BACKENDS chain ran on (its head), when the
# ingestor would not pick it by itself: prints nothing when there is no chain,
# when the head was deleted with the RGB GPU decoders, or when it is the
# ingestor variant's own decoder (_DEFAULT_DECODER in the ingestor's
# config.py), so only a real per-host choice such as qsv-nv12 is pinned.
envgen_carried_decoder() {
    local chain head variant default
    chain="$(envgen_read "$1" BABA_DECODER_BACKENDS)" || return 0
    head="${chain%%,*}"; head="${head// /}"
    variant="$(envgen_read "$1" BABA_INGESTOR_VARIANT || envgen_read "$1" BABA_VARIANT || echo cpu)"
    case "$variant" in
        nvidia) default="ffmpeg-nvdec-nv12" ;;
        intel)  default="vaapi-nv12" ;;
        *)      default="software" ;;
    esac
    case "$head" in
        "$default") ;;
        *-nv12|software) printf '%s' "$head" ;;
    esac
}

# Remove the retired keys from an existing .env, each with the comment block
# directly above it (a "# ===" section rule and everything above it stays).
# The head of an old BABA_DECODER_BACKENDS chain carries over as
# BABA_DECODER_BACKEND when it is a per-host choice (envgen_carried_decoder),
# so a host pinned to qsv-nv12 keeps it. Backed up once, every change printed, written
# through the existing inode (.env may be bind-mounted). Run before
# envgen_merge_missing, which would otherwise seed BABA_DECODER_BACKEND empty.
envgen_retire() {
    local target="$1"
    if [[ ! -f "$target" ]]; then
        c_err "envgen_retire: $target does not exist"
        return 1
    fi
    local k found=()
    for k in "${ENVGEN_RETIRED_KEYS[@]}"; do
        grep -qE "^${k}=" "$target" && found+=("$k")
    done
    (( ${#found[@]} == 0 )) && return 0

    envgen_backup "$target"

    local chain carried=""
    if chain="$(envgen_read "$target" BABA_DECODER_BACKENDS)" \
            && [[ -z "$(envgen_read "$target" BABA_DECODER_BACKEND || echo "")" ]]; then
        carried="$(envgen_carried_decoder "$target")"
        case "${chain%%,*}" in
            *-nv12|software) ;;
            *) c_warn "  BABA_DECODER_BACKENDS=$chain: its first decoder no longer exists — the variant's decoder applies" ;;
        esac
    fi

    local tmp
    tmp=$(mktemp)
    ENVGEN_RETIRED="${ENVGEN_RETIRED_KEYS[*]}" ENVGEN_CARRIED="$carried" awk '
        BEGIN {
            n = split(ENVIRON["ENVGEN_RETIRED"], ks, " ")
            for (i = 1; i <= n; i++) retired[ks[i]] = 1
            carried = ENVIRON["ENVGEN_CARRIED"]
        }
        function flush(   i) { for (i = 1; i <= nb; i++) out(buf[i]); nb = 0 }
        function out(l) { print l; last_blank = (l == "") }
        /^[ \t]*#/ {
            if ($0 ~ /^#[ \t]*=+[ \t]*$/) { flush(); out($0); next }
            buf[++nb] = $0; next
        }
        /^[ \t]*$/ {
            flush()
            if (!(dropped && last_blank)) out($0)
            dropped = 0; next
        }
        {
            key = $0; sub(/=.*/, "", key)
            if (key in retired) {
                nb = 0; dropped = 1
                if (key == "BABA_DECODER_BACKENDS" && carried != "") out("BABA_DECODER_BACKEND=" carried)
                next
            }
            if (key == "BABA_DECODER_BACKEND" && carried != "") { nb = 0; dropped = 1; next }
            flush(); out($0); dropped = 0
        }
        END { flush() }' "$target" > "$tmp"
    cat "$tmp" > "$target"
    rm -f "$tmp"

    [[ -n "$carried" ]] && c_ok "  BABA_DECODER_BACKEND: <empty> → $carried (head of the retired chain)"
    for k in "${found[@]}"; do
        c_ok "  $k: removed (the variant decides)"
    done
    return 0
}

# Set each named key to the value of the shell variable of the same name,
# in place: keys not named, comments and order stay as they are. Every
# change is printed, and the file is backed up once before the first one.
# Written through the existing inode, because .env may be bind-mounted.
envgen_apply() {
    local target="$1"; shift
    local k old new backed_up=0 changed=0 tmp
    for k in "$@"; do
        new="${!k-}"
        old="$(envgen_read "$target" "$k" || echo "")"
        [[ "$old" == "$new" ]] && continue
        if (( backed_up == 0 )); then
            envgen_backup "$target"
            backed_up=1
        fi
        tmp=$(mktemp)
        ENVGEN_KEY="$k" ENVGEN_VAL="$new" awk '
            BEGIN { k = ENVIRON["ENVGEN_KEY"]; v = ENVIRON["ENVGEN_VAL"] }
            index($0, k "=") == 1 { last = NR }
            { line[NR] = $0 }
            END {
                for (i = 1; i <= NR; i++) print (i == last ? k "=" v : line[i])
                if (!last) print k "=" v
            }' "$target" > "$tmp"
        cat "$tmp" > "$target"
        rm -f "$tmp"
        case "$k" in
            *PASSWORD*|*SECRET*) c_ok "  $k: $([[ -n "$old" ]] && echo replaced || echo set)" ;;
            *) c_ok "  $k: ${old:-<empty>} → ${new:-<empty>}" ;;
        esac
        changed=$((changed+1))
    done
    (( changed == 0 )) && c_dim "  Configuration unchanged."
    return 0
}

# Hard-coded defaults for the merge path. Anything not listed gets an
# empty value, which is the right call for "let the service's own
# fallback handle it".
envgen_default_for() {
    case "$1" in
        BABA_UID)                           echo "1000";;
        BABA_GID)                           echo "1000";;
        BABA_GO2RTC_API_USER)               echo "baba";;
        BABA_VARIANT)                       echo "cpu";;
        BABA_INTEL_RENDER_GID)              command -v detect_render_gid >/dev/null 2>&1 && detect_render_gid || echo "110";;
        BABA_DETECTOR_MODEL)                echo "/models/rtdetrv2-r18.onnx";;
        BABA_DETECTOR_MODEL_FAMILY)         echo "dfine";;
        BABA_DETECTOR_BATCH)                echo "8";;
        BABA_DETECTOR_BATCH_WAIT_MS)        echo "20";;
        BABA_DETECTOR_CONF)                 echo "0.10";;
        BABA_DETECTOR_IOU)                  echo "0.45";;
        BABA_DETECTOR_INPUT_SIZE)           echo "640";;
        BABA_DEVICE_ID)                     echo "0";;
        BABA_TRACKER_CLASSES)               echo "0,1,2,3,5,7,14,15,16";;
        BABA_TRACKER_FPS)                   echo "15";;
        BABA_EMBEDDER_MODEL)                echo "/models/osnet_x0_25_msmt17.onnx";;
        BABA_FACE_DETECTOR_MODEL)           echo "/models/face_yunet.onnx";;
        BABA_FACE_EMBEDDER_MODEL)           echo "/models/face_auraface.onnx";;
        BABA_EVENT_TRACK_TIMEOUT_MS)        echo "5000";;
        BABA_EVENT_MIN_TRACK_LIFETIME_MS)   echo "1500";;
        BABA_EVENT_MIN_OBSERVATIONS)        echo "5";;
        BABA_THUMBNAIL_MAX_WIDTH)           echo "640";;
        BABA_EVENT_DWELL_MS)                echo "30000";;
        BABA_RECORDER_SEGMENT_SECONDS)      echo "300";;
        POSTGRES_USER)                      echo "baba";;
        POSTGRES_DB)                        echo "baba";;
        BABA_API_PORT)                      echo "8080";;
        BABA_ADMIN_USERNAME)                echo "admin";;
        BABA_COOKIE_SECURE)                 echo "false";;
        BABA_AI_AUTO_DESCRIBE)              echo "0";;
        BABA_AI_AUTO_DESCRIBE_INTERVAL_S)   echo "120";;
        BABA_AI_AUTO_DESCRIBE_BATCH)        echo "5";;
        *) echo "";;
    esac
}

# Read a key from an existing .env into stdout. Returns empty + 1 if
# absent. Tolerant of `KEY=value`, `KEY="value"`, and trailing comments.
envgen_read() {
    local target="$1" key="$2"
    if [[ ! -f "$target" ]]; then return 1; fi
    local line
    line=$(grep -E "^${key}=" "$target" | tail -1) || return 1
    if [[ -z "$line" ]]; then return 1; fi
    # Strip "KEY=", optional surrounding quotes, optional trailing
    # whitespace. Don't strip in-value spaces — passwords may legit
    # contain them, even if we don't generate ones that do.
    local val="${line#${key}=}"
    val="${val%\"}"; val="${val#\"}"
    val="${val%\'}"; val="${val#\'}"
    printf '%s' "$val"
}
